var dir_0f209cb6edd1adfe0f5da9d77d3b84bd =
[
    [ "amdb_api.h", "amdb__api_8h.html", "amdb__api_8h" ],
    [ "ar_spf_cmd_api.h", "ar__spf__cmd__api_8h.html", "ar__spf__cmd__api_8h" ],
    [ "audioss_dsp_mem_api.h", "audioss__dsp__mem__api_8h.html", "audioss__dsp__mem__api_8h" ],
    [ "codec_metadata_api.h", "codec__metadata__api_8h.html", "codec__metadata__api_8h" ],
    [ "common_enc_dec_api.h", "common__enc__dec__api_8h.html", "common__enc__dec__api_8h" ],
    [ "congestion_buf_api.h", "congestion__buf__api_8h.html", "congestion__buf__api_8h" ],
    [ "contexts_api.h", "contexts__api_8h.html", "contexts__api_8h" ],
    [ "detection_cmn_api.h", "detection__cmn__api_8h.html", "detection__cmn__api_8h" ],
    [ "dtmf_detection_api.h", "dtmf__detection__api_8h.html", "dtmf__detection__api_8h" ],
    [ "imcl_fwk_intent_api.h", "imcl__fwk__intent__api_8h.html", "imcl__fwk__intent__api_8h" ],
    [ "jitter_buf_api.h", "jitter__buf__api_8h.html", "jitter__buf__api_8h" ],
    [ "media_fmt_api.h", "media__fmt__api_8h.html", null ],
    [ "media_fmt_api_basic.h", "media__fmt__api__basic_8h.html", "media__fmt__api__basic_8h" ],
    [ "media_fmt_api_ext.h", "media__fmt__api__ext_8h.html", "media__fmt__api__ext_8h" ],
    [ "metadata_api.h", "metadata__api_8h.html", "metadata__api_8h" ],
    [ "module_cmn_api.h", "module__cmn__api_8h.html", "module__cmn__api_8h" ],
    [ "module_cmn_shmem_api.h", "module__cmn__shmem__api_8h.html", "module__cmn__shmem__api_8h" ],
    [ "rd_sh_mem_client_api.h", "rd__sh__mem__client__api_8h.html", "rd__sh__mem__client__api_8h" ],
    [ "rd_sh_mem_ep_api.h", "rd__sh__mem__ep__api_8h.html", "rd__sh__mem__ep__api_8h" ],
    [ "rtm_logging_api.h", "rtm__logging__api_8h.html", "rtm__logging__api_8h" ],
    [ "vocoder_cmn_api.h", "vocoder__cmn__api_8h.html", "vocoder__cmn__api_8h" ],
    [ "wr_sh_mem_client_api.h", "wr__sh__mem__client__api_8h.html", "wr__sh__mem__client__api_8h" ],
    [ "wr_sh_mem_ep_api.h", "wr__sh__mem__ep__api_8h.html", "wr__sh__mem__ep__api_8h" ]
];